### ISSUE TITLE
Schema.org transform issues

### ISSUE THREAD

**Issue by valentinedwv** [CINERGI/geoportal-server-catalog#17]
semicolon in id?
http://cinergi.sdsc.edu/geoportal/rest/metadata/item/22941afcd4b148cab135d2a92f5fe198/html

double quote in descriptions:
https://search.google.com/structured-data/testing-tool/u/0/#url=http%3A%2F%2Fcinergi.sdsc.edu%2Fgeoportal%2Frest%2Fmetadata%2Fitem%2Fbbbb14211d634329835cb8e208cbd355%2Fhtml

**Comment by valentinedwv** [comment]
Did we solve this?

**Comment by smrgeoinfo** [comment]
Looks like not.  22941afcd4b148cab135d2a92f5fe198 is a pretty worthless record, almost all default values, and the distribution link is a local SQL connection string. 

I'll update the xslt.

**Comment by smrgeoinfo** [comment]
I fixed the problems and pushed a new version of ISO19139ToSchemaOrgDataset1.0.xslt  with commit 3c9e4a4b9a7cd5070dbb397879da6780bd9252ef on the  cinergi26newISOeval branch.
