### ISSUE TITLE
Cinergi facets in UI are incomplete

### ISSUE THREAD

**Issue by smrgeoinfo** [CINERGI/geoportal-server-catalog#26]
only Activity, Equipment and Feature3 are showing up under CINERGI facets.  The hierarchy construction is not working for some reason.

**Comment by valentinedwv** [comment]
It does not like  order:{_term:'asc'}:
 props:{size:1000,
             order:{_term:'asc'}},

**Comment by smrgeoinfo** [comment]
Looks like this is fixed by commit daab5a6ccf2ea8423284a3949da78a7316d4fefa.  The CINERGI keywords are still showing up sorted alphabetically which is good. Can the list show up without the top level 'Category' node in the facet tree?
